import type { Metadata } from "next";

import { css } from "@root/styled-system/css";

import { dmSans } from "@/styles/fonts";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} ${css({
          color: "text-primary",
          bg: "bg-tertiary",
          textStyle: "body-base",
        })}`}
      >
        {children}
      </body>
    </html>
  );
}
